In [1]:
[[12,123,123,34,123],[],[]]

[[12, 123, 123, 34, 123], [], []]

In [7]:
import numpy

In [6]:
n=numpy.arange(27)

In [9]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [12]:
m=numpy.asarray([[12,123,123,34,123],[],[]])
m

array([[12, 123, 123, 34, 123], [], []], dtype=object)

In [13]:
import cv2

In [16]:
im_g=cv2.imread("smallgray.png",0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [21]:
cv2.imwrite("newimg.png",0)

True

In [22]:
im_g[2,4]

182

In [20]:
for i in im_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [24]:
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [25]:
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [28]:
imh=numpy.hstack((im_g,im_g))
imh

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [29]:
imv=numpy.vstack((im_g,im_g))
imv

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [31]:
lst=numpy.hsplit(im_g,5)
lst

[array([[187],
        [198],
        [209]], dtype=uint8), array([[158],
        [125],
        [134]], dtype=uint8), array([[104],
        [255],
        [255]], dtype=uint8), array([[121],
        [255],
        [ 97]], dtype=uint8), array([[143],
        [147],
        [182]], dtype=uint8)]

In [33]:
lstv=numpy.vsplit(im_g,3)
lstv

[array([[187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182]], dtype=uint8)]